### ISSUE TITLE
Add ListVariableSource for branch names

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-subversion#5]
Similar to this: https://github.com/Inedo/inedox-git/blob/master/Git/GitHub.InedoExtension/ListVariableSources/BranchListVariableSource.cs

SVN is different in that it uses paths, so it may be simply getting a list of the subdirectories in the source path `branches/*`

**Comment by apxltd** [comment]
Not feasible/worthwhile with current SVN libraries/approach
