### ISSUE TITLE
Add Branch property to checkout operation

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-subversion#7]
Behavior:

- if `Branch` property is specified *and* `SourcePath` is empty, assume the source path is `branches/<branch>`, otherwise keep current behavior
- change "repository root" description of `SourcePath` to "repository root or branch root"

**Comment by apxltd** [comment]
Unneeded; we can just recommend that `$Branch` is always prefixed with `branches/` such that you say `$Branch=trunk` or `$Branch=branches/feature-1`, etc
